USE NoteStack;

CREATE TABLE Note (
	id				INT			PRIMARY KEY AUTO_INCREMENT,
	title			VARCHAR(50) NOT NULL,
	text			VARCHAR(50) NOT NULL,
	dateCreated		DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dateModified	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP
);
